// Generated by CoffeeScript 1.7.1
var TendinaExamples;

TendinaExamples = (function() {
  function TendinaExamples() {
    this.initTendinaExamples();
    this.initHljs();
  }

  TendinaExamples.prototype.initTendinaExamples = function() {
    return $('#my-menu').tendina();
  };

  TendinaExamples.prototype.initHljs = function() {
    return hljs.initHighlightingOnLoad();
  };

  return TendinaExamples;

})();

$(function() {
  return new TendinaExamples;
});
