// Generated by CoffeeScript 1.7.1
var TendinaExamples;

TendinaExamples = (function() {
  function TendinaExamples() {
    this.$smallHeaderLink = $('.small-header a');
    this.initTendinaExamples();
    this.initHljs();
    this._bindEvents();
  }

  TendinaExamples.prototype.initTendinaExamples = function() {
    $('#my-menu').tendina();
    $('#my-menu-1').tendina({
      onHover: true,
      hoverDelay: 500
    });
    return $('#my-menu-2').tendina({
      activeMenu: $('.opeth')
    });
  };

  TendinaExamples.prototype.initHljs = function() {
    return hljs.initHighlightingOnLoad();
  };

  TendinaExamples.prototype.swapFakeContentText = function(el) {
    var $fakeContent, clickedText;
    clickedText = $(el).text();
    $fakeContent = $(el).parents('.example-menu-container').siblings('.fake-content');
    return $fakeContent.find('h2').text(clickedText);
  };

  TendinaExamples.prototype.hideSmallTopbar = function() {
    return $('.small-header').removeClass('active');
  };

  TendinaExamples.prototype.showSmallTopbar = function() {
    return $('.small-header').addClass('active');
  };

  TendinaExamples.prototype.scrollSpy = function() {
    var section, sections, _i, _len, _results;
    sections = ['usage', 'examples', 'download'];
    _results = [];
    for (_i = 0, _len = sections.length; _i < _len; _i++) {
      section = sections[_i];
      if ($(window).scrollTop() > $("#" + section).position().top) {
        this.$smallHeaderLink.removeClass('selected');
        _results.push(this.$smallHeaderLink.filter("[data-name='" + section + "']").addClass('selected'));
      } else {
        _results.push(void 0);
      }
    }
    return _results;
  };

  TendinaExamples.prototype._isMobile = function() {
    return /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent);
  };

  TendinaExamples.prototype._bindEvents = function() {
    $('.menu-example ul li > ul li a').on('click', (function(_this) {
      return function(event) {
        event.preventDefault();
        return _this.swapFakeContentText(event.currentTarget);
      };
    })(this));
    $(window).on('scroll', (function(_this) {
      return function() {
        if (!_this._isMobile()) {
          _this.scrollSpy();
        }
        if ($(window).scrollTop() > $('#usage').position().top) {
          return _this.showSmallTopbar();
        } else {
          return _this.hideSmallTopbar();
        }
      };
    })(this));
    return this.$smallHeaderLink.on('click', (function(_this) {
      return function(event) {
        _this.$smallHeaderLink.removeClass('selected');
        return $(event.currentTarget).addClass('selected');
      };
    })(this));
  };

  return TendinaExamples;

})();

$(function() {
  return window.tendinaExamples = new TendinaExamples;
});
